version: '3'
services:

  redis:
    container_name: ooad-redis
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - 6379
    volumes:
      - redis-data:/data
    depends_on:
      - db

  app:
    container_name: ooad-django
    build: ./mysite
    command: >
      bash -c "python manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      daphne -b 0.0.0.0 -p 8000 mysite.asgi:application"
    restart: always
    expose:
      - 8000
    volumes:
      - django-data:/mysite
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
      - redis

  db:
    container_name: ooad-postgres
    restart: always
    expose:
      - 5432
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  redis-data:
  pgdata:
  django-data:

