version: '3'
services:

  nginx:
    container_name: ooad-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - ./nginx/log:/var/log/nginx
      - django-data:/docker_django
    networks:
      - proxy
    depends_on:
      - app
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_NETWORK=${VIRTUAL_NETWORK}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  app:
    build:
      context: ./mysite
      dockerfile: Dockerfile.prod
    networks:
      - proxy
      - default

networks:
  proxy:
    external:
      name: self-nginx-proxy
