version: '3'
services:

  # docker run --name some-redis  -p 6379:6379  -d redis redis-server --appendonly yes
  nginx:
    container_name: ooad-nginx
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/log:/var/log/nginx
      - django-data:/docker_django
    networks:
      - proxy
    depends_on:
      - app
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_NETWORK=${VIRTUAL_NETWORK}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  redis:
    container_name: ooad-redis
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    depends_on:
      - db

  app:
    container_name: ooad-django
    build:
      context: ./mysite
      args:
        - SECRET_KEY=${SECRET_KEY}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: bash -c "daphne -b 0.0.0.0 -p 8000 mysite.asgi:application"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - django-data:/mysite
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - proxy
      - default
    depends_on:
      - db
      - redis

  db:
    container_name: ooad-postgres
    restart: always
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  redis-data:
  pgdata:
  django-data:

networks:
  proxy:
    external:
      name: self-nginx-proxy
