version: '3'
services:

  # docker run --name some-redis  -p 6379:6379  -d redis redis-server --appendonly yes
  nginx:
    container_name: ooad-nginx
    build: ./nginx
    restart: always
    volumes:
      - ./log:/var/log/nginx
#    networks:
#      - proxy
    depends_on:
      - app
    ports:
      - "80:80"
    env_file:
      - nginx.env

  redis:
    container_name: ooad-redis
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    depends_on:
      - db

  app:
    container_name: ooad-django
    build: ./mysite
    command: bash -c "daphne -b 0.0.0.0 -p 8000 mysite.asgi:application"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - django-data:/mysite
    env_file:
      - django_secrets.env
    depends_on:
      - db
      - redis

  db:
    container_name: ooad-postgres
    restart: always
    ports:
      - "5432:5432"
    image: postgres
    env_file:
      - django_secrets.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  redis-data:
  pgdata:
  django-data:

