# Generated by Django 3.2 on 2021-04-14 03:23

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_room_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[(game.models.Room.StatusType['ORGANIZE'], game.models.Room.StatusType['ORGANIZE']), (game.models.Room.StatusType['PLAYING'], game.models.Room.StatusType['PLAYING']), (game.models.Room.StatusType['END'], game.models.Room.StatusType['END'])], default='organize', max_length=8),
        ),
    ]
