# Generated by Django 3.2 on 2021-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('organize', 'Organize'), ('playing', 'Playing'), ('END', 'End')], default='organize', max_length=8),
        ),
    ]
