# Generated by Django 3.2 on 2021-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210425_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('organize', 'Organize'), ('playing', 'Playing'), ('end', 'End')], default='organize', max_length=8),
        ),
    ]
