# Generated by Django 3.2 on 2021-05-09 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_alter_gameroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players_data', through='game.PlayerData', to=settings.AUTH_USER_MODEL),
        ),
    ]
