# Generated by Django 3.2 on 2021-05-09 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0007_alter_gameroom_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(blank=True, through='game.PlayerData', to=settings.AUTH_USER_MODEL),
        ),
    ]
