# Generated by Django 3.2.3 on 2021-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_gameroom_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='volume',
            field=models.SmallIntegerField(default=4),
        ),
    ]
