FROM node:15.14-buster AS node
RUN mkdir -p /mysite
COPY . /mysite/
WORKDIR /mysite/frontend
RUN yarn install
RUN yarn build

FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /mysite
COPY --from=node /mysite /mysite
WORKDIR /mysite

RUN pip install -r requirements.txt
