FROM python:3.7
ENV PYTHONUNBUFFERED 1

ADD requirements.txt /mysite/requirements.txt
RUN pip install -r /mysite/requirements.txt
ADD . /mysite
WORKDIR /mysite

ARG POSTGRES_PASSWORD
ARG SECRET_KEY
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV SECRET_KEY=$SECRET_KEY

RUN python manage.py collectstatic
# RUN python manage.py makemigrations
# RUN python manage.py migrate
