# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server Project Check

on:
  pull_request:
    branches: [ develop ]
    
defaults:
  run:
    working-directory: ./mysite/frontend

jobs:
  Frontend Build Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '15.x'
      - run: yarn install
      - run: CI=false yarn build

